import { Navbar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Lato, Roboto } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Mimansha Swarup's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-dark-500`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
